 ====================================================
 SQL PROJECT BASED ON A DATABSE 
 ====================================================

USE sql_store;

 1️⃣ List all customers with their total number of orders
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id;

2️⃣ Total revenue generated by the store
SELECT 
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi;

 3️⃣ Top 5 highest earning customers
SELECT 
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(oi.quantity * oi.unit_price) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY customer_name
ORDER BY total_spent DESC
LIMIT 5;

4️⃣ Most frequently ordered products
SELECT 
    p.name AS product_name,
    SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id
ORDER BY total_units_sold DESC;

5️⃣ Monthly revenue trend (window function)
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(oi.unit_price * oi.quantity) AS monthly_revenue,
    SUM(SUM(oi.unit_price * oi.quantity)) OVER (ORDER BY DATE_FORMAT(o.order_date, '%Y-%m')) AS running_total
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month;

6️⃣ Customers who have never placed an order
SELECT 
    CONCAT(first_name, ' ', last_name) AS customer_name
FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);

7️⃣ Average order value
SELECT 
    AVG(order_value) AS avg_order_value
FROM (
    SELECT 
        o.order_id,
        SUM(oi.unit_price * oi.quantity) AS order_value
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id
) AS t;

8️⃣ Revenue contribution by each state
SELECT 
    c.state,
    SUM(oi.unit_price * oi.quantity) AS state_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.state
ORDER BY state_revenue DESC;

9️⃣ Shipper performance - average delivery time
SELECT
    s.name AS shipper,
    AVG(DATEDIFF(o.shipped_date, o.order_date)) AS avg_delivery_days
FROM shippers s
JOIN orders o ON s.shipper_id = o.shipper_id
WHERE o.shipped_date IS NOT NULL
GROUP BY s.shipper_id;

🔟 Products that are low in stock (< 20 units)
SELECT 
    product_id,
    name,
    quantity_in_stock
FROM products
WHERE quantity_in_stock < 20;
